export const classNames = {
  startButton: 'a',
  scoreText: 'b',
  scoreAddText: 'c',
  timeText: 'd',
  levelLabel: 'e',
  livesText: 'f',
  movesDiv: 'g',
  tutorialOption: 'h',
  highscoreOption: 'i',
  undoButton: 'j',
  mainUi: 'k',
  finalScoreScreen: 'l',
  casualEndScreen: 'm',
  mainMenu: 'n',
  selectedOption: 'o',
  stateCasualMode: 'p',
  glyph: 'q',
  stateTutorial: 'r',
  endText: 'z',
  monetizationPopup: '_a',

  // Classes which are not used in JS:
  screen: 's',
  scoreDiv: 't',
  stat: 'u',
  metricLabel: 'v',
  timeDiv: 'w',
  clickable: 'x',
  option: 'y'
}