export const classNames = {
  stateStart: 'a',
  stateMainMenu: 'b',
  statePlaying: 'c',
  stateTutorial: 'd',
  stateEnd: 'e',
  ui: 'f',
  levelLabel: 'g',
  scoreDiv: 'h',
  dynamic: 'i',
  scoreText: 'j',
  scoreAddText: 'k',
  timeDiv: 'l',
  timeText: 'm',
  clickable: 'n',
  startButton: 'o',
  glyph: 'p',
  metricLabel: 'q',
  finalScoreDiv: 'r',
  option: 's',
  tutorialOption: 't',
  highscoreOption: 'u',
  livesText: 'v',
  selectedOption: 'w'
}