export const ATTR_POSITION = 'a'
export const ATTR_NORMAL = 'b'
export const ATTR_UV = 'c'

export const U_MODELMATRIX = 'd'
export const U_VIEWMATRIX = 'e'
export const U_PROJECTIONMATRIX = 'g'
export const U_NORMALMATRIX = 'h'
export const U_CAMERAPOSITION = 'i'
export const U_COLOR = 'j'
export const U_ACTIVE = 'k'
export const U_TIME = 'l'
export const U_TEXTURE = 'm'
export const U_WRAP_START = 'n'
export const U_WRAP_LENGTH = 'o'